version: '3.8'

services:
  nginx:
    image: nginx:1.19.7-alpine
    networks:
      - front
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf/proxy_params:/etc/nginx/proxy_params
      - ./nginx-conf/sites-enabled:/etc/nginx/sites-enabled
      - ./data/www:/var/www
      - ./certs:/etc/letsencrypt

  web:
    container_name: web
    build: .
    restart: always
    networks:
      - front
      - back
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      MONGODB_URI: ${MONGODB_URI}
      REDIS_PASS: ${REDIS_PASS}
    depends_on:
      - mongodb

  mongodb:
    image: dannyben/alpine-mongo:latest
    restart: always
    networks:
      - back
    expose:
      - '27017'
    volumes:
      - ./mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
      - MONGO_INITDB_DATABASE=${MONGO_DB}

  redis:
    image: redis:6.2-alpine
    restart: always
    networks:
      - back
    expose:
      - "6379"
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASS}
    volumes: 
      - ./data:/data

networks:
  front:
    driver: bridge
  back:
    driver: bridge