version: '3'

services:
  web:
    container_name: app
    build: .
    ports:
      - "90:5000"
    depends_on:
      - mongodb

  mongodb:
    image: dannyben/alpine-mongo:latest
    expose:
      - '27017'
    volumes:
      - ./mongo_data:/data/db


