version: '3'

services:
  web:
    container_name: app
    build: .
    ports:
      - "90:5000"
    depends_on:
      - redis

  redis:
   
    image: redis
    ports:
      - "6379:6379"

  mongodb:
    container_name: mongodb
    image: skazuki/alpine-mongodb
    restart: always
  mongo-express:
    container_name: mongo-express
    image: skazuki/alpine-mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - VCAP_APP_HOST=0.0.0.0
      - VCAP_APP_PORT=8081
    ports:
      - 8081:8081
    links:
      - mongodb:mongodb