version: '3'

services:
  web:
    container_name: app
    build: .
    ports:
      - "90:5000"
    depends_on:
      - redis
      - mongodb

  redis:
    image: redis
    ports:
      - "6379:6379"

  mongodb:
    container_name: mongodb
    image: aymen94/mongodb-alpine
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: local
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGODB_DB: production
      MONGODB_USER: user
      MONGODB_PASSWORD: pass
    volumes:
      - ./mongo_data:/data/db
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh:ro
