version: '3'

services:
  web:
    container_name: app
    build: .
    ports:
      - "90:5000"
    depends_on:
      - redis
      - mongodb

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo_data:/data/db
      
