version: '3.8'

services:
  nginx:
    image: nginx:1.19.7-alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx-conf/proxy_params:/etc/nginx/proxy_params
      - ./nginx-conf/sites-enabled:/etc/nginx/sites-enabled
      - ./data/www:/var/www
      - ./certs:/etc/letsencrypt

  web:
    container_name: web
    build: .
    ports:
      - "90:5000"
    depends_on:
      - mongodb

  mongodb:
    image: dannyben/alpine-mongo:latest
    expose:
      - '27017'
    volumes:
      - ./mongo_data:/data/db
