name: docker-compose-actions-workflow

on:
  push:
    branches:
      - IGD-78-Add-github-secrets
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        working-directory: ./tests 
        run: REDIS_HOST=redis REDIS_PORT=6379 MONGODB_URI='mongodb://mongodb:27017/' docker-compose up -d 
      - name: Check if docker-compose has the service 'web'
        run: docker compose ps --services | grep web
      - name: Check if docker-compose has the service 'redis'
        run: docker compose ps --services | grep redis
      - name: Test containers functionality
        uses: cypress-io/github-action@v6
        env:
          CYPRESS_BASE_URL: http://localhost:5000
        with:
          working-directory: ./.github/tests

